version: '3'
services:
  db:
    image: postgres:12.3-alpine
    container_name: postgres
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_DB: orb
      POSTGRES_PASSWORD: bioshock1
      POSTGRES_USER: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - pg-data:/var/lib/postgresql/data/pgdata
    networks:
      - backend

  orb-server:
    build:
      context: orb-server
    container_name: orb-server
    environment:
      POSTGRES_HOST: db
    ports:
      - 8080:8080
    depends_on:
      - db
    restart: always
    networks:
      - backend
      - frontend

  orb-client:
    build:
      context: orb-client
      args:
        REACT_APP_API_BASE_URL: http://127.0.0.1:8080/api
    container_name: orb-client
    ports:
      - 3000:80
    restart: always
    depends_on:
      - orb-server
    networks:
      - frontend

volumes:
  pg-data:

networks:
  backend:
  frontend: